import type { WorkoutDay } from "./types";

export const WORKOUT_DAYS: WorkoutDay[] = [
  {
    id: "PUSH_A",
    index: 1,
    code: "D-01",
    title: "PUSH A",
    focus: "CHEST FOCUS",
    exercises: [
      {
        id: "incline_db_bench",
        name: "Incline Bench Press (Dumbbell)",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        priority: true,
        muscles: ["chest", "shoulders", "triceps"],
      },
      {
        id: "flat_chest_press_machine",
        name: "Flat Chest Press Machine",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        priority: true,
        muscles: ["chest", "triceps"],
      },
      {
        id: "pec_fly_nautilus",
        name: "Pec Fly (Nautilus)",
        sets: 3,
        repRangeLow: 8,
        repRangeHigh: 12,
        priority: true,
        muscles: ["chest"],
      },
      {
        id: "smith_jm_press",
        name: "Smith Machine JM Press",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["triceps", "chest"],
      },
      {
        id: "standing_lat_raise_machine",
        name: "Standing Lateral Raise Machine",
        sets: 3,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["shoulders"],
      },
    ],
  },
  {
    id: "PULL_A",
    index: 2,
    code: "D-02",
    title: "PULL A",
    focus: "BACK THICKNESS + BICEPS",
    exercises: [
      {
        id: "t_bar_row",
        name: "T Bar Row",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["back"],
      },
      {
        id: "iso_lateral_row",
        name: "Iso-Lateral Row (Machine)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["back"],
      },
      {
        id: "lat_pulldown_cable",
        name: "Lat Pulldown (Cable)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["back"],
      },
      {
        id: "ez_bar_curls",
        name: "EZ Bar Curls",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["biceps"],
      },
      {
        id: "bayesian_cable_curl",
        name: "Bayesian Cable Curl",
        sets: 3,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["biceps"],
      },
    ],
  },
  {
    id: "LEGS_A",
    index: 3,
    code: "D-03",
    title: "LEGS A",
    focus: "QUAD FOCUS",
    exercises: [
      {
        id: "pendulum_squat",
        name: "Pendulum Squat",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["quads", "glutes"],
      },
      {
        id: "hack_squat",
        name: "Hack Squat",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["quads", "glutes"],
      },
      {
        id: "leg_extension_machine_a",
        name: "Leg Extension (Machine)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["quads"],
      },
      {
        id: "sissy_squat",
        name: "Sissy Squat",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 15,
        muscles: ["quads"],
      },
      {
        id: "seated_leg_curl",
        name: "Seated Leg Curl (Machine)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["hamstrings"],
      },
      {
        id: "ab_crunch_machine",
        name: "Ab Crunch Machine",
        sets: 2,
        repRangeLow: 10,
        repRangeHigh: 15,
        muscles: ["core"],
      },
    ],
  },
  {
    id: "PUSH_B",
    index: 4,
    code: "D-04",
    title: "PUSH B",
    focus: "SHOULDER / TRICEP FOCUS",
    exercises: [
      {
        id: "shoulder_press_machine",
        name: "Shoulder Press Machine",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["shoulders", "triceps"],
      },
      {
        id: "incline_press_machine",
        name: "Incline Press Machine",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        priority: true,
        muscles: ["chest", "shoulders"],
      },
      {
        id: "upper_cable_crossover",
        name: "Upper Cable Crossover",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        priority: true,
        muscles: ["chest"],
      },
      {
        id: "cable_lateral_raise",
        name: "Cable Lateral Raise",
        sets: 2,
        repRangeLow: 10,
        repRangeHigh: 15,
        muscles: ["shoulders"],
      },
      {
        id: "weighted_dips",
        name: "Weighted Dips",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["chest", "triceps"],
      },
      {
        id: "bar_tricep_pushdown",
        name: "Bar Tricep Pushdown",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["triceps"],
      },
      {
        id: "overhead_tricep_ext_bar",
        name: "Overhead Tricep Extension (Straight Bar)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["triceps"],
      },
    ],
  },
  {
    id: "PULL_B",
    index: 5,
    code: "D-05",
    title: "PULL B",
    focus: "BACK WIDTH + BICEPS + REAR DELTS",
    exercises: [
      {
        id: "weighted_pullup",
        name: "Weighted Pullup",
        sets: 2,
        repRangeLow: 6,
        repRangeHigh: 10,
        muscles: ["back", "biceps"],
      },
      {
        id: "mid_row_machine",
        name: "Mid Row Machine",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["back"],
      },
      {
        id: "lat_pullover_nautilus",
        name: "Lat Pullover (Nautilus)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["back"],
      },
      {
        id: "cable_rear_delt_fly",
        name: "Cable Rear Delt Fly",
        sets: 3,
        repRangeLow: 10,
        repRangeHigh: 15,
        muscles: ["shoulders"],
      },
      {
        id: "preacher_curl_machine",
        name: "Preacher Curl (Machine)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["biceps"],
      },
      {
        id: "hammer_curl_db",
        name: "Hammer Curl (Dumbbell)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["biceps"],
      },
    ],
  },
  {
    id: "LEGS_B",
    index: 6,
    code: "D-06",
    title: "LEGS B",
    focus: "HAMSTRING / GLUTE FOCUS",
    exercises: [
      {
        id: "lying_leg_curl",
        name: "Lying Leg Curl (Machine)",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["hamstrings"],
      },
      {
        id: "single_leg_rdl",
        name: "Single Leg RDL",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["hamstrings", "glutes"],
      },
      {
        id: "bulgarian_split_squat",
        name: "Bulgarian Split Squat",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 12,
        muscles: ["quads", "glutes"],
      },
      {
        id: "leg_extension_machine_b",
        name: "Leg Extension (Machine)",
        sets: 2,
        repRangeLow: 10,
        repRangeHigh: 15,
        muscles: ["quads"],
      },
      {
        id: "hanging_leg_raise",
        name: "Hanging Leg Raise",
        sets: 2,
        repRangeLow: 8,
        repRangeHigh: 15,
        muscles: ["core"],
      },
      {
        id: "decline_situp",
        name: "Decline Sit-up",
        sets: 2,
        repRangeLow: 10,
        repRangeHigh: 15,
        muscles: ["core"],
      },
    ],
  },
];

export const WEEKLY_VOLUME: Array<{ muscle: string; sets: number }> = [
  { muscle: "CHEST", sets: 11 },
  { muscle: "SHOULDERS", sets: 10 },
  { muscle: "TRICEPS", sets: 8 },
  { muscle: "BACK", sets: 12 },
  { muscle: "BICEPS", sets: 9 },
  { muscle: "QUADS", sets: 12 },
  { muscle: "HAMS", sets: 6 },
  { muscle: "CORE", sets: 6 },
];

export const TOTAL_WEEKLY_SETS = WEEKLY_VOLUME.reduce((sum, v) => sum + v.sets, 0);

export function getDayById(id: string): WorkoutDay | undefined {
  return WORKOUT_DAYS.find((d) => d.id === id);
}

export function getExerciseById(exerciseId: string) {
  for (const day of WORKOUT_DAYS) {
    const ex = day.exercises.find((e) => e.id === exerciseId);
    if (ex) return { exercise: ex, day };
  }
  return null;
}

export function allExercises() {
  return WORKOUT_DAYS.flatMap((d) => d.exercises.map((e) => ({ exercise: e, day: d })));
}
